#61 add mock product
otakedev/ceihm-groupe-7 pull request #80
Opened 2021-02-15 09:27 UTC by HouriRuben

Un bon boeuf bourguignon mais pas que 
![image](https://user-images.githubusercontent.com/42980612/107928274-6703e800-6f78-11eb-8020-f27fed55d65c.png)

2021-02-15 09:46 UTC, YounesAbdennadher requested changes

2021-02-15 09:46 UTC, YounesAbdennadher commented on lib/mocks/ingredients_mock.dart
> +  "name": "Pomme de terre",
Tu veux le laisser au singulier ?

2021-02-15 09:46 UTC, YounesAbdennadher commented on lib/mocks/products_mock.dart
>          "quantity": "80g",
Tu mélanges des quantités en grammes et en %. Il faut choisir.

2021-02-15 09:46 UTC, YounesAbdennadher commented on lib/mocks/products_mock.dart
> +        "name": "Noisette",
singulier ?

2021-02-15 09:46 UTC, YounesAbdennadher commented on lib/mocks/products_mock.dart
> +        "description": "Issue de L'Agriculture Biologique"
Issu pour le masculin, issue pour le féminin. "Provient" serait plus approprié du coup.

2021-02-15 09:46 UTC, YounesAbdennadher commented on lib/mocks/products_mock.dart
> +    "description": "Pate à tartiner à base de cacahuètes",
Pâte*

2021-02-15 09:46 UTC, YounesAbdennadher commented on lib/mocks/products_mock.dart
> +    "name": "Les Saladières Niçoise",
niçoises* ? sans majuscule et avec un s

2021-02-15 09:46 UTC, YounesAbdennadher commented on lib/mocks/products_mock.dart
> +        "name": "Pâtes",
Pâte est plus un produit qu'un ingrédient mais pas très important

2021-02-15 09:46 UTC, YounesAbdennadher commented on lib/mocks/products_mock.dart
> +        "name": "Agriculture Biologique",
Qu'est ce qui se passe s'il y a 0 labels ? Le cas est pris en compte ?

2021-02-15 11:13 UTC, Betsara-MARCELLIN approved these changes

2021-02-17 22:06 UTC, YounesAbdennadher commented on lib/mocks/products_mock.dart
> +        "name": "Agriculture Biologique",
@HouriRuben up ?

2021-02-17 22:13 UTC, YounesAbdennadher requested changes

2021-02-17 22:13 UTC, YounesAbdennadher commented on lib/models/product_model.dart
> +    this.labels,
Pourquoi avoir enlever le @required ?

2021-02-17 22:18 UTC, HouriRuben commented on lib/mocks/products_mock.dart
> +        "name": "Agriculture Biologique",
La section label disparait

2021-02-17 22:18 UTC, HouriRuben commented on lib/models/product_model.dart
> +    this.labels,
Le cas ou il n'y a pas de Labels

2021-02-17 22:18 UTC, YounesAbdennadher commented on lib/mocks/products_mock.dart
> +        "name": "Agriculture Biologique",
Ok

2021-02-17 22:18 UTC, YounesAbdennadher commented on lib/models/product_model.dart
> +    this.labels,
Niquel

2021-02-17 22:19 UTC, YounesAbdennadher approved these changes

2021-02-20 16:00 UTC, merged